# assistant_router.py
# This is the FastAPI router that exposes the assistant to the outside world.
# It defines the single POST /assistant/query endpoint that the frontend
# or any API client calls to ask the assistant a question.
# It takes a plain-English question, runs it through the LangGraph graph,
# and returns a plain-English answer.

from fastapi import APIRouter, HTTPException
from pydantic import BaseModel
from langchain_core.messages import HumanMessage

# Import the compiled LangGraph graph — this is the brain of the assistant
from crew_ops.assistant.graph import assistant_graph

# Create the router with a prefix and tag for FastAPI docs
router = APIRouter(
    prefix="/assistant",
    tags=["Assistant"],
)


# ── Request Model ─────────────────────────────────────────────────────────────
# This defines the shape of the JSON body the client sends.
# Example: { "query": "Who is available to fly tomorrow?" }

class QueryRequest(BaseModel):
    # The plain-English question from the OCC manager
    query: str


# ── Response Model ────────────────────────────────────────────────────────────
# This defines the shape of the JSON response we send back.
# Example: { "answer": "3 crew members are available tomorrow: ..." }

class QueryResponse(BaseModel):
    # The plain-English answer generated by the assistant
    answer: str


# ── POST /assistant/query ─────────────────────────────────────────────────────
# This is the only endpoint the assistant exposes.
# Flow:
#   1. Receive the manager's question as a string
#   2. Wrap it in a HumanMessage and build the initial graph state
#   3. Run the LangGraph graph — it calls tools, processes results, synthesizes
#   4. Extract the final_answer from the graph output
#   5. Return it as a plain-English string

@router.post("/query", response_model=QueryResponse)
async def query_assistant(request: QueryRequest):
    """
    Ask the CrewOps Assistant a question about crew, flights, FTL, or rosters.

    Send a plain-English question and receive a plain-English answer.
    The assistant will automatically query the database using the appropriate tools.
    """
    # Validate that the query is not empty
    if not request.query.strip():
        raise HTTPException(status_code=400, detail="Query cannot be empty.")

    try:
        # Build the initial state for the graph
        # messages starts with the user's question as a HumanMessage
        # tool_results and final_answer start empty — the graph fills them in
        initial_state = {
            "messages": [HumanMessage(content=request.query)],
            "tool_results": {},
            "final_answer": "",
        }

        # Run the full LangGraph graph synchronously
        # The graph will: agent → tools (if needed) → agent → synthesizer → END
        result = await assistant_graph.ainvoke(initial_state)

        # Extract the final answer the synthesizer wrote
        answer = result.get("final_answer", "").strip()

        # If for some reason the graph produced no answer, return a safe fallback
        if not answer:
            answer = "I was unable to find an answer to your question. Please try rephrasing."

        return QueryResponse(answer=answer)

    except Exception as e:
        # Temporary: print full traceback to server console for debugging
        import traceback
        traceback.print_exc()
        raise HTTPException(
            status_code=500,
            detail=f"Assistant error: {str(e)}"
        )